project:
  type: book
  output-dir: docs
  # execute:
  #   cache: true
  #   freeze: auto
  
book:
  title: "Social Network Analysis Workshop"
  author: "Dr Clemens Jarnach"
  date: "03/18/2026"
  repo-url: https://github.com/clemensjarnach/social_network_analysis_workshop
  chapters:
    - index.qmd
    - 1_what_are_networks.qmd
    - 2_slides.qmd
    - 3_r_fundamentals.qmd
    - 4_creating_your_first_network.qmd
    - 5_analysing_networks_in_R.qmd
    - 6_network_data.qmd
    - 7_statistical_models_for_networks.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    split-by: chapter  
    number-depth: 1
    theme: cosmo
    highlight-style: atom-one
    code-block-bg: "#f0f0f0"
    code-block-border-left: "#045a8d"
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    code-copy: true
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68
  # pdf:
  #   documentclass: scrbook
  #   always_allow_html: true
  #   include-in-header:
  #     - text: |
  #         \usepackage{dcolumn}
    
pdf-engine: lualatex
